apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-cert
  namespace: monitoring
spec:
  dnsNames:
    - "megaitservices.com.ng"
    - "*.megaitservices.com.ng"
  secretName: monitoring-cert-secret
  # commonName: '*.megaitservices.com.ng'
  issuerRef:
    name: wildcard-issuer
    kind: ClusterIssuer
