apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sharkapp-cert
  namespace: sharkapp
spec:
  dnsNames:
    - "megaitservices.com.ng"
    - "*.megaitservices.com.ng"
  secretName: sharkapp-cert-secret
  # commonName: '*.megaitservices.com.ng'
  issuerRef:
    name: wildcard-issuer
    kind: ClusterIssuer
