apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: wildcard-issuer
spec:
  acme:
    email: israeltademola@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: wildcard-issuer-key
    solvers:
    - dns01:
        cloudflare:
          email: israeltademola@gmail.com
          apiKeySecretRef:
            name: cloudflare-secret
            key: api-key
      # selector:
      #   dnsZones:
      #   - '*.megaitservices.com.ng'
